# Sitio m√≠nimo oss.coderic.org - Open Source / proyectos libres
title: "Coderic"
description: "Proyectos open source y software libre por Coderic"
url: "https://oss.coderic.org"
baseurl: ""

remote_theme: Coderic/jekyll-theme-coderic

plugins:
  - jekyll-feed
  - jekyll-sitemap

markdown: kramdown
permalink: pretty
